# --- Bootloader Path ---
BOOTLOADER_PATH="boot"

# --- Target Disk Configuration ---
INSTALL_DISK="/dev/sdb"
BOOT_PARTITION="/dev/sdb1"
ROOT_PARTITION="/dev/sdb2"
CHROOT_DIR="/mnt"

# --- Hardware Configuration ---
CPU="intel"          # options: amd, intel
GPU0="nvidia"         # options: amd, intel, nvidia, nvidia_foss
GPU1="none"        # secondary GPU

# --- System Identity ---
HOSTNAME="asrockpg4d5"
USERNAME="artofmusic"
PASSWORD="Artm1993#!"

# --- Localization & Regional ---
MIRROR_COUNTRY="ca"
USER_LOCALE="en_CA.UTF-8"
KEYMAP="us"
TIMEZONE="America/Toronto"

# --- Features ---
USE_CHAOTIC="y"
