#!/bin/sh

# REAPER Install Directory
REAPER_INSTALL_DIR="$HOME/.reaper/REAPER"

# REAPER cmd arguments
LD_PATH=$REAPER_INSTALL_DIR/FFMPEG:$LD_PATH LD_LIBRARY_PATH=$REAPER_INSTALL_DIR/FFMPEG:$LD_LIBRARY_PATH WINEFSYNC=1 "$REAPER_INSTALL_DIR/reaper" %F
