#!/usr/bin/bash

# Path to where YaVST winebuild resides.
PATH_TO_WINE_BUILD="${HOME}/.plugins/YaVST"

# Wineasio binary package
WINEASIO_PKG="wineasio-1.3.0-2-x86_64.pkg.tar.zst"

# Download archive
wget "https://builds.garudalinux.org/repos/chaotic-aur/x86_64/${WINEASIO_PKG}"

# Extract archive
tar --use-compress-program=unzstd -xvf "${PWD}/${WINEASIO_PKG}"

# Move WineASIO binary
cp -rf "${PWD}/usr/lib" "${PATH_TO_WINE_BUILD}"

# Remove leftovers
rm "${WINEASIO_PKG}"
rm -rf "${PWD}/usr"
rm .*

# read WINEPREFIX from environment, with fallback if unset
WINEPREFIX=${WINEPREFIX:=~/.wine}

# exit if any command fails
set -e

# make sure the WINEPREFIX directory exists
if [ ! -d "${WINEPREFIX}" ]; then
    wineboot -u
fi

# define possible locations for wineasio DLLs

u64=(
"${PATH_TO_WINE_BUILD}/lib/wine/x86_64-unix/wineasio64.dll.so"
"${PATH_TO_WINE_BUILD}/lib64/wine/x86_64-unix/wineasio64.dll.so"
"${PATH_TO_WINE_BUILD}/lib/x86_64-linux-gnu/wine/x86_64-unix/wineasio64.dll.so"
)

# try to register 64bit DLL
for u in ${u64[@]}; do
    w=$(echo ${u} | sed -e 's|/x86_64-unix/wineasio64.dll.so|/x86_64-windows/wineasio64.dll|g')
    if [ -e "${u}" ] && [ -e "${w}" ]; then
        cp -v "${w}" "${WINEPREFIX}/drive_c/windows/system32"
        wine64 regsvr32 "${u}"
        break
    fi
done
