#!/bin/sh

# Path for the YaVST bundle
BUNDLE_PATH="$HOME/.audioplugins/YaVST"
WINE_VER=9.21
YABRIDGE_VER=5.1.1

if [[ "$#" == "1" ]]; then
    if [[ "$1" == "install-multilib" ]]; then
        # Make YaVST bundle directory and wine installation directory
        mkdir -p "$BUNDLE_PATH"

        # Download and install Yabridge
        wget "https://github.com/robbert-vdh/yabridge/releases/download/${YABRIDGE_VER}/yabridge-${YABRIDGE_VER}.tar.gz"

        # Regenerate yabridge install
        if [[ -d "$BUNDLE_PATH/yabridge" ]]; then
            rm -rf "$BUNDLE_PATH/yabridge"
        fi

        if [[ -d "$HOME/.local/share/yabridge" ]]; then
            rm -rf "$HOME/.local/share/yabridge"
        fi

        # Make Yabridge Directories
        mkdir -p "$BUNDLE_PATH/yabridge"
        mkdir -p "$HOME/.local/share/yabridge"

        # Archive handling for yabridge
        tar -xvzf "${PWD}/yabridge-${YABRIDGE_VER}.tar.gz"
        rm "${PWD}/yabridge-${YABRIDGE_VER}.tar.gz"

        # Directory handling for yabridge
        mv "${PWD}/yabridge"/* "$HOME/.local/share/yabridge"
        rm -rf "${PWD}/yabridge"

        # Create Link to Yabridge directory
        ln -sf "$HOME/.local/share/yabridge" "$BUNDLE_PATH/yabridge"

        # Download and unzip wine (default install of wine, requires a linux distro with 32bit libraries installed)
        wget "https://github.com/Kron4ek/Wine-Builds/releases/download/${WINE_VER}/wine-${WINE_VER}-staging-tkg-amd64.tar.xz"

        # Remove old wine install
        if [[ -d "$PWD/YaVST" ]]; then
            rm -rf YaVST/{bin,lib,share,wine-tkg-config.txt}
        fi

        # Archive handling for wine
        tar -xvJf "${PWD}/wine-${WINE_VER}-staging-tkg-amd64.tar.xz"
        rm "${PWD}/wine-${WINE_VER}-staging-tkg-amd64.tar.xz"

        # Directory handling for wine
        mv "${PWD}/wine-${WINE_VER}-staging-tkg-amd64"/* "$BUNDLE_PATH"
        rm -rf "${PWD}/wine-${WINE_VER}-staging-tkg-amd64"

    elif [[ "$1" == "install-wow64" ]]; then
        # Make YaVST bundle directory and wine installation directory
        mkdir -p "$BUNDLE_PATH"

        # Download and install Yabridge
        wget "https://github.com/robbert-vdh/yabridge/releases/download/${YABRIDGE_VER}/yabridge-${YABRIDGE_VER}.tar.gz"

        # Regenerate yabridge install
        if [[ -d "$PWD/YaVST/yabridge" ]]; then
            rm -rf "$BUNDLE_PATH/yabridge"
        fi

        if [[ -d "$HOME/.local/share/yabridge" ]]; then
            rm -rf "$HOME/.local/share/yabridge"
        fi

        # Make Yabridge Directories
        mkdir -p "$BUNDLE_PATH/yabridge"
        mkdir -p "$HOME/.local/share/yabridge"

        # Archive handling for yabridge
        tar -xvzf "${PWD}/yabridge-${YABRIDGE_VER}.tar.gz"
        rm "${PWD}/yabridge-${YABRIDGE_VER}.tar.gz"

        # Directory handling for yabridge
        mv "${PWD}/yabridge"/* "$HOME/.local/share/yabridge"
        rm -rf "${PWD}/yabridge"

        # Create Link to Yabridge directory
        ln -sf "$HOME/.local/share/yabridge" "$BUNDLE_PATH/yabridge"

        # Download and unzip wine (WOW64: still considered experimental, but will work on pure-64bit linux systems)
        wget "https://github.com/Kron4ek/Wine-Builds/releases/download/${WINE_VER}/wine-${WINE_VER}-staging-tkg-amd64-wow64.tar.xz"

        # Remove old wine install
        if [[ -d "$PWD/YaVST" ]]; then
            rm -rf YaVST/{bin,lib,share,wine-tkg-config.txt}
        fi

        # Archive handling for wine
        tar -xvJf "${PWD}/wine-${WINE_VER}-staging-tkg-amd64-wow64.tar.xz"
        rm "${PWD}/wine-${WINE_VER}-staging-tkg-amd64-wow64.tar.xz"

        # Directory handling for wine
        mv "${PWD}/wine-${WINE_VER}-staging-tkg-amd64-wow64"/* "$BUNDLE_PATH"
        rm -rf "${PWD}/wine-${WINE_VER}-staging-tkg-amd64-wow64"

    elif [[ "$1" == "setenv" ]]; then
        echo "" >> $HOME/.bashrc
        echo "## Setup Yabridge VST Environment (For Bazzite and other immutable distros)" >> $HOME/.bashrc
        echo "declare -r BUNDLE_PATH=\"$BUNDLE_PATH\"" >> $HOME/.bashrc
        echo "export WINEVERPATH=\"\$BUNDLE_PATH\"" >> $HOME/.bashrc
        echo "export PATH=\"\$BUNDLE_PATH/bin:\$HOME/.local/share/yabridge:\$PATH\"" >> $HOME/.bashrc
        echo "export WINEDLLPATH=\"\$BUNDLE_PATH/lib/wine/fakedlls\"" >> $HOME/.bashrc
        echo "export WINELOADER=\"\$BUNDLE_PATH/bin/wine\"" >> $HOME/.bashrc
        echo "export WINESERVER=\"\$BUNDLE_PATH/bin/wineserver\"" >> $HOME/.bashrc
        echo "export LD_LIBRARY_PATH=\"\$BUNDLE_PATH/lib:\$LD_LIBRARY_PATH\"" >> $HOME/.bashrc

    elif [[ "$1" == "uninstall" ]]; then
        rm -rvf "$BUNDLE_PATH"
        rm -rvf "$HOME/.local/share/yabridge"

    else
        # Help / usage message
        echo "Usage: yavst_setup.sh <argument> <multilib/wow64>"
        echo "install-multilib - Installs the bundle (this is the default option for systems with 32bit libraries installed)"
        echo "install-wow64 - Installs the bundle (this is the option for systems with a pure 64-bit environment: CAUTION THIS IS STILL EXPERIMENTAL)"
        echo "setenv - Creates the relevant environment variables in $HOME/.bashrc"
        echo "uninstall - Uninstalls the bundle"

    fi

else
    echo "Please type in a valid argument for this script"

fi
